<a href="https://colab.research.google.com/github/WHT-git/1018-homework/blob/main/1018hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [219]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [220]:
data = pd.read_csv('/content/drive/My Drive/機器學習作業/CSV/bank-full.csv')
data.head(3)

age           job  marital  education  ... pdays  previous poutcome   y
0   58    management  married   tertiary  ...    -1         0  unknown  no
1   44    technician   single  secondary  ...    -1         0  unknown  no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown  no

[3 rows x 17 columns]

In [221]:
data.shape

(45211, 17)

In [222]:
#沒有錯誤資料
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [223]:
le = LabelEncoder()

In [224]:
data['job'] = le.fit_transform(data['job'])
data['marital'] = le.fit_transform(data['marital'])
data['education'] = le.fit_transform(data['education'])
data['default'] = le.fit_transform(data['default'])
data['housing'] = le.fit_transform(data['housing'])
data['loan'] = le.fit_transform(data['loan'])
data['contact'] = le.fit_transform(data['contact'])
data['month'] = le.fit_transform(data['month'])
data['poutcome'] = le.fit_transform(data['poutcome'])
data['y'] = le.fit_transform(data['y'])
data

age  job  marital  education  ...  pdays  previous  poutcome  y
0       58    4        1          2  ...     -1         0         3  0
1       44    9        2          1  ...     -1         0         3  0
2       33    2        1          1  ...     -1         0         3  0
3       47    1        1          3  ...     -1         0         3  0
4       33   11        2          3  ...     -1         0         3  0
...    ...  ...      ...        ...  ...    ...       ...       ... ..
45206   51    9        1          2  ...     -1         0         3  1
45207   71    5        0          0  ...     -1         0         3  1
45208   72    5        1          1  ...    184         3         2  1
45209   57    1        1          1  ...     -1         0         3  0
45210   37    2        1          1  ...    188        11         1  0

[45211 rows x 17 columns]

In [225]:
#由資料網站上顯示之資料定義
#因此將y分離(output_target)
target_y = data['y'].values
data_in = data.drop('y', 1)

In [226]:
from sklearn.preprocessing import StandardScaler

In [227]:
ss = StandardScaler()

In [228]:
scaled_data = ss.fit_transform(data_in)
scaled_data

array([[ 1.60696496, -0.10381968, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [ 0.28852927,  1.42400783,  1.3683719 , ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.74738448, -0.71495069, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       ...,
       [ 2.92540065,  0.20174582, -0.27576178, ...,  1.43618859,
         1.05047333, -0.56617504],
       [ 1.51279098, -1.02051619, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.37068857, -0.71495069, -0.27576178, ...,  1.4761376 ,
         4.52357654, -1.57724822]])

In [229]:
import numpy.linalg as linalg

In [230]:
cov_mat = np.cov(scaled_data.T)

In [231]:
eig_vals, eig_vecs = linalg.eig(cov_mat)

In [232]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort()
eig_pairs.reverse()

In [233]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(16,1), eig_pairs[1][1].reshape(16,1)))
Y = scaled_data.dot(matrix_w)
Y

array([[-0.78890923,  1.31830434],
       [-0.73076082,  1.2819238 ],
       [-0.82883489,  2.38356872],
       ...,
       [ 1.57891358, -0.5852589 ],
       [-0.94353462,  0.40619616],
       [ 3.93389431,  0.3128333 ]])

In [234]:
from sklearn.decomposition import PCA

In [235]:
pca = PCA(n_components=16)

In [236]:
#比對是否相同
Y_sklearn = pca.fit_transform(scaled_data)
Y_sklearn

array([[-0.78890923, -1.31830434,  0.77622944, ..., -0.91095236,
         0.78134598,  0.01807685],
       [-0.73076082, -1.2819238 , -1.05772434, ..., -0.80708433,
         0.84246101, -0.00626468],
       [-0.82883489, -2.38356872, -0.29819299, ..., -0.1503869 ,
        -0.56243756, -0.01018423],
       ...,
       [ 1.57891358,  0.5852589 ,  2.50001712, ...,  0.28133803,
         1.33432119,  0.68063531],
       [-0.94353462, -0.40619616,  1.43027295, ...,  0.42936521,
         0.55606185,  0.03677162],
       [ 3.93389431, -0.3128333 ,  0.60783749, ...,  1.6215404 ,
        -0.12475192,  0.10213318]])

In [237]:
x_feature = pca.fit_transform(scaled_data)

In [238]:
x_feature

array([[-0.78890923, -1.31830434,  0.77622944, ..., -0.91095236,
         0.78134598,  0.01807685],
       [-0.73076082, -1.2819238 , -1.05772434, ..., -0.80708433,
         0.84246101, -0.00626468],
       [-0.82883489, -2.38356872, -0.29819299, ..., -0.1503869 ,
        -0.56243756, -0.01018423],
       ...,
       [ 1.57891358,  0.5852589 ,  2.50001712, ...,  0.28133803,
         1.33432119,  0.68063531],
       [-0.94353462, -0.40619616,  1.43027295, ...,  0.42936521,
         0.55606185,  0.03677162],
       [ 3.93389431, -0.3128333 ,  0.60783749, ...,  1.6215404 ,
        -0.12475192,  0.10213318]])

In [239]:
pca.explained_variance_ratio_

array([0.14884565, 0.10538756, 0.09316483, 0.07623335, 0.07041535,
       0.06341351, 0.06101426, 0.05818671, 0.05714418, 0.05247551,
       0.05138942, 0.04808036, 0.0388857 , 0.03427101, 0.03239391,
       0.00869869])

In [240]:
X_train, X_test, Y_train, Y_test = train_test_split(x_feature, target_y, test_size=0.1)

## 方法一

In [241]:
lr = LinearRegression(normalize=True)

In [242]:
lr.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [243]:
lr.intercept_

0.11691907255997785

In [244]:
lr.coef_

array([ 0.02709109,  0.03282522, -0.0005542 ,  0.05667228, -0.04212302,
       -0.01003158,  0.09614139,  0.00462379, -0.03136298,  0.01604941,
        0.0031045 ,  0.03648168, -0.01455215,  0.02514471,  0.00923062,
        0.05332653])

In [245]:
lr.predict(X_test)

array([0.14644944, 0.04130628, 0.15927862, ..., 0.09217946, 0.08090122,
       0.48676275])

In [246]:
Y_test

array([0, 0, 0, ..., 0, 0, 0])

In [247]:
lr.score(X_test,Y_test)

0.22671190506471084

In [248]:
from sklearn.model_selection import cross_val_score

In [249]:
scores = cross_val_score(lr, X_test, Y_test, cv=10, scoring='r2')
scores

array([0.19504014, 0.22241678, 0.13593952, 0.24255657, 0.23680823,
       0.22308732, 0.31558684, 0.22593785, 0.21139671, 0.16457995])

In [250]:
scores.mean()

0.21733499068371373

## 方法二

In [251]:
from sklearn.linear_model import RidgeCV

In [252]:
rg = RidgeCV(alphas=(1.0, 0.1, 0.01, 0.005, 0.0025, 0.001, 0.00025), normalize=True)

In [253]:
rg.fit(X_train,Y_train)

RidgeCV(alphas=array([1.0e+00, 1.0e-01, 1.0e-02, 5.0e-03, 2.5e-03, 1.0e-03, 2.5e-04]),
        cv=None, fit_intercept=True, gcv_mode=None, normalize=True,
        scoring=None, store_cv_values=False)

In [254]:
rg.score(X_test,Y_test)

0.22657840670913698

In [255]:
rg.alpha_

0.01

## 方法三

In [256]:
from sklearn.linear_model import LassoCV

In [257]:
ls = LassoCV(alphas=(1.0, 0.1, 0.01, 0.005, 0.0025, 0.001, 0.00025), normalize=True)
ls.fit(X_train, Y_train)
ls.score(X_test, Y_test)

0.08632405422277667

## 方法四

In [258]:
from sklearn.linear_model import ElasticNet, ElasticNetCV

In [259]:
en = ElasticNet(alpha=0.001, l1_ratio=0.8, normalize=True)
en_scores = cross_val_score(en, X_test, Y_test, cv=7, scoring='r2')
encv = ElasticNetCV(alphas=(0.1, 0.01, 0.005, 0.0025, 0.001), l1_ratio=(0.1, 0.25, 0.5, 0.75, 0.8), normalize=True)
encv.fit(X_train, Y_train)

ElasticNetCV(alphas=(0.1, 0.01, 0.005, 0.0025, 0.001), copy_X=True, cv=None,
             eps=0.001, fit_intercept=True,
             l1_ratio=(0.1, 0.25, 0.5, 0.75, 0.8), max_iter=1000, n_alphas=100,
             n_jobs=None, normalize=True, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [260]:
encv.score(X_test,Y_test)

0.007210702930552371

## 方法五

In [261]:
from sklearn.preprocessing import PolynomialFeatures

In [264]:
pf = PolynomialFeatures(degree=2)
Xp = pf.fit_transform(X_train)

In [267]:
lr.fit(Xp, Y_train)
lr.score(Xp, Y_train)

0.28247602427887175